[package]
name = "aircard"
version = "1.2.1"
edition = "2024"
description = "Native Windows AirCard client"
license = "MIT"

[dependencies]
anyhow = "1.0"
idevice = { version = "0.1.65", features = ["remote_pairing", "mdns", "tcp", "rsd", "afc", "syslog_relay", "tunnel_tcp_stack"] }
mdns-sd = "0.20"
tokio = { version = "1.53", features = ["rt-multi-thread", "net", "time", "sync"] }
uuid = { version = "1.24", features = ["v4"] }
base64 = "0.23"
eframe = { version = "0.33", default-features = false, features = ["default_fonts", "accesskit", "wgpu"] }
egui = "0.33"
wgpu = { version = "27.0.1", default-features = true }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
libloading = "0.8"
plist = "1"
regex = "1"
rfd = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = { version = "2", default-features = false, features = ["deflate"] }

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
